/**
 * Mock constants for Jest tests
 */
export const GTFS_URLS = {};
export const MAP_CONFIG = {};
export const REFRESH_INTERVALS = {};
export const ROUTE_COLORS = {};
export const APP_CONFIG = {};
export const OTP_CONFIG = {
  BASE_URL: '',
  TIMEOUT_MS: 15000,
  USE_MOCK_IN_DEV: false,
};
export const LOCATIONIQ_CONFIG = {
  API_KEY: 'test-key',
  BASE_URL: 'https://us1.locationiq.com/v1',
  BARRIE_BOUNDS: '-79.85,44.25,-79.55,44.50',
  BARRIE_CENTER: { lat: 44.3894, lon: -79.6903 },
  DEBOUNCE_MS: 300,
  MAX_RESULTS: 5,
};
export const ROUTING_CONFIG = {
  MAX_TRANSFERS: 2,
  MAX_WALK_TO_TRANSIT: 800,
  MAX_WALK_FOR_TRANSFER: 400,
  WALK_SPEED: 1.2,
  TRANSFER_PENALTY: 180,
  MIN_TRANSFER_TIME: 60,
  WALK_DISTANCE_BUFFER: 1.3,
  MAX_ACTUAL_WALK_DISTANCE: 1200,
  MAX_ITINERARIES: 3,
  TIME_WINDOW: 7200,
  MAX_TRIP_DURATION: 7200,
  MAX_WAIT_TIME: 3600,
};
export const TRIP_UI_CONFIG = {
  HIGH_WALK_THRESHOLD: 800,
  LEAVING_SOON_MINUTES: 5,
  DEBOUNCE_DELAY_MS: 300,
  TRIP_CACHE_TTL_MS: 300000,
  MAX_STOPS_DISPLAY: 150,
};
