import { BUS_HUBS } from './busHubs';

const CITY_FACILITIES_URL = 'https://www.barrie.ca/community-recreation-environment/facilities-venues';
const CITY_ADDRESS_DATA_URL = 'https://public-barrie.opendata.arcgis.com/datasets/address-points/about';
const BARRIE_LIBRARY_URL = 'https://www.barrielibrary.ca/about-bpl/branches';
const SCDSB_URL = 'https://www.scdsb.on.ca/school_search';
const SMCDSB_URL = 'https://www.smcdsb.on.ca/our_schools/school_directory';
const OPENSTREETMAP_URL = 'https://www.openstreetmap.org/copyright';

const landmark = ({
  id,
  name,
  address,
  latitude,
  longitude,
  category,
  aliases = [],
  priority = 50,
  sourceUrl = CITY_ADDRESS_DATA_URL,
}) => ({
  id,
  name,
  address,
  coordinate: { latitude, longitude },
  category,
  aliases,
  priority,
  sourceUrl,
});

const HUB_METADATA = {
  'allandale-terminal': {
    address: '20 Essa Road',
    aliases: [
      'Allandale Hub',
      'Allandale Terminal',
      'Barrie Transit Terminal',
      'Barrie bus terminal',
      'new transit terminal',
    ],
    priority: 100,
  },
  'downtown-hub': {
    address: 'Maple Avenue, Downtown Barrie',
    aliases: [
      'downtown',
      'downtown Barrie',
      'downtown terminal',
      'downtown transit hub',
      'Maple Avenue terminal',
      'old downtown terminal',
    ],
    priority: 100,
  },
  'park-place-terminal': {
    address: '100 Mapleview Drive East',
    aliases: ['Park Place shopping centre', 'Park Place mall', 'south terminal'],
    priority: 90,
  },
  'georgian-college': {
    address: '1 Georgian Drive',
    aliases: ['Georgian', 'Georgian campus', 'Georgian College Barrie campus', 'GC'],
    priority: 95,
  },
  'barrie-south-go': {
    address: '833 Yonge Street',
    aliases: ['South GO', 'Barrie South station', 'Barrie South GO station', 'BSGO'],
    priority: 100,
  },
  'georgian-mall': {
    address: '509 Bayfield Street',
    aliases: ['Georgian shopping centre', 'Georgian Mall terminal'],
    priority: 85,
  },
  rvh: {
    address: '201 Georgian Drive',
    aliases: [
      'Royal Victoria',
      'Royal Victoria Hospital',
      'Royal Victoria Regional Health Centre',
      'Barrie hospital',
      'hospital',
    ],
    priority: 100,
  },
  'peggy-hill-team-community-centre': {
    address: '171 Mapleton Avenue',
    aliases: [
      'Peggy Hill',
      'Peggy Hill community centre',
      'PHTCC',
      'Holly rec centre',
      'Holly community centre',
      'Holly pool',
    ],
    priority: 85,
  },
};

const HUB_LANDMARKS = BUS_HUBS.map((hub) => {
  const metadata = HUB_METADATA[hub.id] || {};
  return landmark({
    id: `hub-${hub.id}`,
    name: hub.displayName,
    address: metadata.address || 'Barrie, Ontario',
    latitude: hub.coordinate.latitude,
    longitude: hub.coordinate.longitude,
    category: hub.id === 'rvh' ? 'healthcare' : 'transit',
    aliases: [hub.shortName, ...(metadata.aliases || [])].filter(Boolean),
    priority: metadata.priority || 80,
    sourceUrl: CITY_ADDRESS_DATA_URL,
  });
});

const CURATED_LANDMARKS = [
  // Regional rail and transit destinations not represented by a Barrie Transit hub.
  landmark({
    id: 'allandale-waterfront-go',
    name: 'Allandale Waterfront GO',
    address: '24 Essa Road',
    latitude: 44.3734097,
    longitude: -79.6860091,
    category: 'transit',
    aliases: ['Allandale GO', 'Waterfront GO', 'Allandale Waterfront station', 'AWGO'],
    priority: 100,
    sourceUrl: OPENSTREETMAP_URL,
  }),

  // City recreation and community facilities.
  landmark({
    id: 'sadlon-arena',
    name: 'Sadlon Arena',
    address: '555 Bayview Drive',
    latitude: 44.33769,
    longitude: -79.67772,
    category: 'recreation',
    aliases: [
      'Sadlon Centre',
      'Sadland Centre',
      'Sadland Arena',
      'Barrie Molson Centre',
      'BMC',
      'Colts arena',
      'Barrie Colts arena',
    ],
    priority: 95,
    sourceUrl: `${CITY_FACILITIES_URL}/sadlon-arena`,
  }),
  landmark({
    id: 'allandale-recreation-centre',
    name: 'Allandale Recreation Centre',
    address: '190 Bayview Drive',
    latitude: 44.36148,
    longitude: -79.68416,
    category: 'recreation',
    aliases: ['Allandale Rec Centre', 'Allandale rec', 'ARC', 'Allandale pool'],
    priority: 85,
    sourceUrl: `${CITY_FACILITIES_URL}/allandale-recreation-centre`,
  }),
  landmark({
    id: 'east-bayfield-community-centre',
    name: 'East Bayfield Community Centre',
    address: '80 Livingstone Street East',
    latitude: 44.41507,
    longitude: -79.70362,
    category: 'recreation',
    aliases: ['East Bayfield Rec Centre', 'East Bayfield rec', 'EBCC', 'East Bayfield pool'],
    priority: 85,
    sourceUrl: `${CITY_FACILITIES_URL}/east-bayfield-community-centre`,
  }),
  landmark({
    id: 'lampman-lane-community-centre',
    name: 'Lampman Lane Community Centre',
    address: '59 Lampman Lane',
    latitude: 44.39089,
    longitude: -79.72623,
    category: 'recreation',
    aliases: ['Lampman Lane Centre', 'Lampman community centre', 'Lampman park'],
    priority: 70,
    sourceUrl: `${CITY_FACILITIES_URL}/lampman-lane-community-centre`,
  }),
  landmark({
    id: 'parkview-centre',
    name: 'Parkview Centre',
    address: '189 Blake Street',
    latitude: 44.39484,
    longitude: -79.66558,
    category: 'community',
    aliases: ['Parkview Community Centre', 'Parkview Seniors Centre'],
    priority: 65,
    sourceUrl: `${CITY_FACILITIES_URL}/parkview-centre`,
  }),
  landmark({
    id: 'eastview-arena',
    name: 'Eastview Arena',
    address: '453 Grove Street East',
    latitude: 44.40516,
    longitude: -79.65908,
    category: 'recreation',
    aliases: ['Eastview rink', 'Eastview ice rink'],
    priority: 70,
    sourceUrl: `${CITY_FACILITIES_URL}/eastview-arena`,
  }),
  landmark({
    id: 'southshore-centre',
    name: 'General John Hayter Southshore Community Centre',
    address: '205 Lakeshore Drive',
    latitude: 44.37408,
    longitude: -79.68036,
    category: 'community',
    aliases: ['Southshore Centre', 'Southshore Community Centre', 'General John Hayter Centre'],
    priority: 70,
    sourceUrl: `${CITY_FACILITIES_URL}/general-john-hayter-southshore-community-centre`,
  }),
  landmark({
    id: 'dorian-parker-centre',
    name: 'Dorian Parker Centre',
    address: '227 Sunnidale Road',
    latitude: 44.39847,
    longitude: -79.71003,
    category: 'community',
    aliases: ['Dorian Parker Community Centre', 'Sunnidale community centre'],
    priority: 60,
    sourceUrl: `${CITY_FACILITIES_URL}/dorian-parker-centre`,
  }),

  // Libraries.
  landmark({
    id: 'library-downtown',
    name: 'Barrie Public Library — Downtown',
    address: '60 Worsley Street',
    latitude: 44.39185,
    longitude: -79.68833,
    category: 'library',
    aliases: ['Downtown library', 'Barrie library', 'BPL Downtown', 'main library'],
    priority: 80,
    sourceUrl: BARRIE_LIBRARY_URL,
  }),
  landmark({
    id: 'library-painswick',
    name: 'Barrie Public Library — Painswick',
    address: '48 Dean Avenue',
    latitude: 44.35433,
    longitude: -79.64748,
    category: 'library',
    aliases: ['Painswick library', 'BPL Painswick', 'Dean Avenue library'],
    priority: 75,
    sourceUrl: BARRIE_LIBRARY_URL,
  }),
  landmark({
    id: 'library-holly',
    name: 'Barrie Public Library — Holly',
    address: '555 Essa Road, Unit 17',
    latitude: 44.33858,
    longitude: -79.71086,
    category: 'library',
    aliases: ['Holly library', 'BPL Holly', 'Essa Road library'],
    priority: 75,
    sourceUrl: BARRIE_LIBRARY_URL,
  }),

  // Secondary and post-secondary schools with commonly used short forms.
  landmark({
    id: 'barrie-north-collegiate',
    name: 'Barrie North Collegiate Institute',
    address: '110 Grove Street East',
    latitude: 44.40073,
    longitude: -79.68965,
    category: 'education',
    aliases: ['Barrie North', 'Barrie North Collegiate', 'BNCI', 'BNC'],
    priority: 75,
    sourceUrl: SCDSB_URL,
  }),
  landmark({
    id: 'college-boreal-barrie',
    name: 'Collège Boréal — Barrie Campus',
    address: '136 Bayfield Street, Suite 100',
    latitude: 44.3923094,
    longitude: -79.693526,
    category: 'education',
    aliases: ['College Boreal', 'Boreal College', 'Boreal Barrie'],
    priority: 65,
    sourceUrl: 'https://collegeboreal.ca/en/emplacement/barrie-site/',
  }),
  landmark({
    id: 'bear-creek-secondary',
    name: 'Bear Creek Secondary School',
    address: '100 Red Oak Drive',
    latitude: 44.33184,
    longitude: -79.73375,
    category: 'education',
    aliases: ['Bear Creek', 'BCSS'],
    priority: 75,
    sourceUrl: SCDSB_URL,
  }),
  landmark({
    id: 'eastview-secondary',
    name: 'Eastview Secondary School',
    address: '421 Grove Street East',
    latitude: 44.4053,
    longitude: -79.66178,
    category: 'education',
    aliases: ['Eastview Secondary', 'Eastview school', 'ESS'],
    priority: 75,
    sourceUrl: SCDSB_URL,
  }),
  landmark({
    id: 'innisdale-secondary',
    name: 'Innisdale Secondary School',
    address: '95 Little Avenue',
    latitude: 44.35937,
    longitude: -79.68542,
    category: 'education',
    aliases: ['Innisdale', 'Innisdale Secondary', 'ISS'],
    priority: 75,
    sourceUrl: SCDSB_URL,
  }),
  landmark({
    id: 'maple-ridge-secondary',
    name: 'Maple Ridge Secondary School',
    address: '225 Prince William Way',
    latitude: 44.3514,
    longitude: -79.60984,
    category: 'education',
    aliases: ['Maple Ridge Secondary', 'Maple Ridge school', 'MRSS'],
    priority: 75,
    sourceUrl: SCDSB_URL,
  }),
  landmark({
    id: 'ecole-nouvelle-alliance',
    name: 'École secondaire catholique Nouvelle-Alliance',
    address: '249 Anne Street North',
    latitude: 44.39612,
    longitude: -79.71567,
    category: 'education',
    aliases: ['Nouvelle Alliance', 'Nouvelle-Alliance', 'ESNA'],
    priority: 70,
    sourceUrl: SMCDSB_URL,
  }),
  landmark({
    id: 'ecole-romeo-dallaire',
    name: 'École secondaire Roméo-Dallaire',
    address: '736 Essa Road',
    latitude: 44.3271,
    longitude: -79.71496,
    category: 'education',
    aliases: ['Romeo Dallaire', 'Roméo-Dallaire', 'ESRD'],
    priority: 70,
    sourceUrl: SCDSB_URL,
  }),
  landmark({
    id: 'st-joan-of-arc',
    name: 'St. Joan of Arc Catholic High School',
    address: '460 Mapleton Avenue',
    latitude: 44.34915,
    longitude: -79.73314,
    category: 'education',
    aliases: ['St Joan of Arc', 'Saint Joan of Arc', 'Joan of Arc', 'JOA', 'St Joans'],
    priority: 75,
    sourceUrl: SMCDSB_URL,
  }),
  landmark({
    id: 'st-joseph-high-school',
    name: "St. Joseph's Catholic High School",
    address: '243 Cundles Road East',
    latitude: 44.41275,
    longitude: -79.68442,
    category: 'education',
    aliases: ['St Josephs', 'Saint Josephs', 'St Joes', 'SJCHS'],
    priority: 75,
    sourceUrl: SMCDSB_URL,
  }),
  landmark({
    id: 'st-peter-secondary',
    name: "St. Peter's Catholic Secondary School",
    address: '201 Ashford Drive',
    latitude: 44.35509,
    longitude: -79.64015,
    category: 'education',
    aliases: ['St Peters', 'Saint Peters', 'St Petes', 'SPCSS', 'SPSS'],
    priority: 75,
    sourceUrl: SMCDSB_URL,
  }),
  landmark({
    id: 'unity-christian-high-school',
    name: 'Unity Christian High School',
    address: '25 Burton Avenue',
    latitude: 44.37191,
    longitude: -79.69011,
    category: 'education',
    aliases: ['Unity Christian', 'Unity high school', 'UCHS'],
    priority: 60,
    sourceUrl: OPENSTREETMAP_URL,
  }),

  // Shopping districts and malls.
  landmark({
    id: 'bayfield-mall',
    name: 'Bayfield Mall',
    address: '320 Bayfield Street',
    latitude: 44.4005796,
    longitude: -79.7033258,
    category: 'shopping',
    aliases: ['Bayfield shopping centre'],
    priority: 75,
    sourceUrl: OPENSTREETMAP_URL,
  }),
  landmark({
    id: 'kozlov-centre',
    name: 'Kozlov Centre',
    address: '400 Bayfield Street',
    latitude: 44.4061751,
    longitude: -79.7067176,
    category: 'shopping',
    aliases: ['Kozlov Mall', 'Kozlov shopping centre'],
    priority: 70,
    sourceUrl: OPENSTREETMAP_URL,
  }),
  landmark({
    id: 'north-barrie-crossing',
    name: 'North Barrie Crossing',
    address: 'Cundles Road East at Highway 400',
    latitude: 44.4141085,
    longitude: -79.6783128,
    category: 'shopping',
    aliases: ['Cundles Crossing', 'Cundles shopping centre', 'North Barrie shopping centre'],
    priority: 70,
    sourceUrl: OPENSTREETMAP_URL,
  }),

  // Civic, cultural, and public-service destinations.
  landmark({
    id: 'barrie-city-hall',
    name: 'Barrie City Hall',
    address: '70 Collier Street',
    latitude: 44.3909467,
    longitude: -79.6863674,
    category: 'civic',
    aliases: ['City Hall', 'Service Barrie', 'Barrie Farmers Market', 'farmers market'],
    priority: 85,
    sourceUrl: 'https://www.barrie.ca/government-news/contact-us',
  }),
  landmark({
    id: 'simcoe-county-courthouse',
    name: 'Simcoe County Courthouse',
    address: '75 Mulcaster Street',
    latitude: 44.39255,
    longitude: -79.68469,
    category: 'civic',
    aliases: ['Barrie courthouse', 'Ontario Court of Justice Barrie', 'Mulcaster courthouse'],
    priority: 75,
  }),
  landmark({
    id: 'provincial-offences-court',
    name: 'Barrie Provincial Offences Court',
    address: '45 Cedar Pointe Drive',
    latitude: 44.38138,
    longitude: -79.7119,
    category: 'civic',
    aliases: ['Provincial court', 'POA court', 'Cedar Pointe court'],
    priority: 65,
  }),
  landmark({
    id: 'five-points-theatre',
    name: 'Five Points Theatre',
    address: '1 Dunlop Street West',
    latitude: 44.38902,
    longitude: -79.690227,
    category: 'culture',
    aliases: ['Five Points', 'Mady Centre', 'Mady Theatre'],
    priority: 70,
    sourceUrl: `${CITY_FACILITIES_URL}/five-points-theatre`,
  }),
  landmark({
    id: 'maclaren-art-centre',
    name: 'MacLaren Art Centre',
    address: '37 Mulcaster Street',
    latitude: 44.3902099,
    longitude: -79.685131,
    category: 'culture',
    aliases: ['MacLaren', 'MacLaren gallery', 'Barrie art gallery'],
    priority: 70,
    sourceUrl: 'https://maclarenart.com/',
  }),
  landmark({
    id: 'meridian-place',
    name: 'Meridian Place',
    address: '30 Simcoe Street',
    latitude: 44.3886605,
    longitude: -79.6875791,
    category: 'culture',
    aliases: ['Memorial Square', 'downtown square'],
    priority: 70,
    sourceUrl: OPENSTREETMAP_URL,
  }),
  landmark({
    id: 'grey-simcoe-foresters-museum',
    name: 'Grey & Simcoe Foresters Regimental Museum',
    address: '36 Mulcaster Street',
    latitude: 44.3899806,
    longitude: -79.6857526,
    category: 'culture',
    aliases: ['Grey and Simcoe Foresters Museum', 'Barrie armoury museum', 'Foresters museum'],
    priority: 55,
    sourceUrl: OPENSTREETMAP_URL,
  }),
  landmark({
    id: 'barrie-native-friendship-centre',
    name: 'Barrie Native Friendship Centre',
    address: '175 Bayfield Street',
    latitude: 44.3949492,
    longitude: -79.6943995,
    category: 'community',
    aliases: ['BNFC', 'Native Friendship Centre', 'Friendship Centre'],
    priority: 65,
    sourceUrl: 'https://www.barrienativefriendshipcentre.ca/',
  }),
  landmark({
    id: 'simcoe-muskoka-health-unit',
    name: 'Simcoe Muskoka District Health Unit',
    address: '15 Sperling Drive',
    latitude: 44.41067,
    longitude: -79.68645,
    category: 'healthcare',
    aliases: ['Health Unit', 'SMDHU', 'public health Barrie', 'Sperling health unit'],
    priority: 75,
    sourceUrl: 'https://www.simcoemuskokahealth.org/HealthUnit/About/Contact/Locations-and-Hours',
  }),
  landmark({
    id: 'hospice-simcoe',
    name: 'Hospice Simcoe',
    address: '336 Penetanguishene Road',
    latitude: 44.41399,
    longitude: -79.6471,
    category: 'healthcare',
    aliases: ['Barrie hospice'],
    priority: 60,
    sourceUrl: 'https://hospicesimcoe.ca/contact/',
  }),

  // Waterfront destinations and major city-wide parks.
  landmark({
    id: 'centennial-park-beach',
    name: 'Centennial Park & Beach',
    address: '65 Lakeshore Drive',
    latitude: 44.3819941,
    longitude: -79.689212,
    category: 'park',
    aliases: ['Centennial Park', 'Centennial Beach', 'Barrie waterfront', 'waterfront beach'],
    priority: 75,
    sourceUrl: OPENSTREETMAP_URL,
  }),
  landmark({
    id: 'heritage-park',
    name: 'Heritage Park',
    address: 'Simcoe Street at Mulcaster Street',
    latitude: 44.3879438,
    longitude: -79.6865173,
    category: 'park',
    aliases: ['Heritage waterfront park', 'downtown waterfront park', 'Heritage splash pad'],
    priority: 70,
    sourceUrl: OPENSTREETMAP_URL,
  }),
  landmark({
    id: 'sunnidale-park',
    name: 'Sunnidale Park & Arboretum',
    address: '265 Sunnidale Road',
    latitude: 44.3975061,
    longitude: -79.7083367,
    category: 'park',
    aliases: ['Sunnidale Park', 'Sunnidale Arboretum', 'Barrie arboretum'],
    priority: 70,
    sourceUrl: OPENSTREETMAP_URL,
  }),
  landmark({
    id: 'minets-point-park',
    name: "Minet's Point Park & Beach",
    address: "Minet's Point Road",
    latitude: 44.3758122,
    longitude: -79.6678523,
    category: 'park',
    aliases: ['Minets Point', 'Minets Point beach', 'Minet Point'],
    priority: 65,
    sourceUrl: OPENSTREETMAP_URL,
  }),
  landmark({
    id: 'johnsons-beach',
    name: "Johnson's Beach Park",
    address: 'Johnson Street at Lakeshore Road',
    latitude: 44.3931169,
    longitude: -79.6575578,
    category: 'park',
    aliases: ['Johnsons Beach', 'Johnson Beach'],
    priority: 65,
    sourceUrl: OPENSTREETMAP_URL,
  }),
  landmark({
    id: 'wilkins-beach',
    name: 'Wilkins Parkette & Beach',
    address: 'Crimson Ridge Road',
    latitude: 44.3693895,
    longitude: -79.6332445,
    category: 'park',
    aliases: ['Wilkins Beach', 'Wilkins Park'],
    priority: 60,
    sourceUrl: OPENSTREETMAP_URL,
  }),
  landmark({
    id: 'tyndale-park',
    name: 'Tyndale Park',
    address: 'Tyndale Road',
    latitude: 44.3740467,
    longitude: -79.644021,
    category: 'park',
    aliases: ['Tyndale Beach', 'Tyndale waterfront'],
    priority: 60,
    sourceUrl: OPENSTREETMAP_URL,
  }),
  landmark({
    id: 'little-lake-park',
    name: 'Little Lake Park',
    address: 'Little Lake Drive',
    latitude: 44.4178854,
    longitude: -79.6629074,
    category: 'park',
    aliases: ['Little Lake', 'Little Lake Barrie'],
    priority: 60,
    sourceUrl: OPENSTREETMAP_URL,
  }),
  landmark({
    id: 'military-heritage-park',
    name: 'Military Heritage Park',
    address: 'Lakeshore Drive at Tiffin Street',
    latitude: 44.373961,
    longitude: -79.6791128,
    category: 'park',
    aliases: ['Military park', 'Southshore waterfront park'],
    priority: 60,
    sourceUrl: OPENSTREETMAP_URL,
  }),
  landmark({
    id: 'the-gables-park',
    name: 'The Gables Park',
    address: 'Tollendal Mill Road',
    latitude: 44.3731069,
    longitude: -79.6599961,
    category: 'park',
    aliases: ['Gables Park', 'The Gables trail'],
    priority: 55,
    sourceUrl: OPENSTREETMAP_URL,
  }),
  landmark({
    id: 'barrie-marina',
    name: 'City of Barrie Marina',
    address: '55 Lakeshore Drive',
    latitude: 44.3845199,
    longitude: -79.6893669,
    category: 'waterfront',
    aliases: ['Barrie Marina', 'city marina', 'waterfront marina'],
    priority: 60,
    sourceUrl: OPENSTREETMAP_URL,
  }),
  landmark({
    id: 'spirit-catcher',
    name: 'Spirit Catcher',
    address: '15 Lakeshore Drive',
    latitude: 44.3865044,
    longitude: -79.6892722,
    category: 'culture',
    aliases: ['Dream Catcher', 'Barrie Spirit Catcher', 'waterfront sculpture'],
    priority: 65,
    sourceUrl: 'https://www.barrie.ca/community-recreation-environment/parks-trails-waterfront/waterfront-features',
  }),
];

export const LOCAL_LANDMARKS = [...HUB_LANDMARKS, ...CURATED_LANDMARKS];

export const LOCAL_LANDMARK_SOURCE_URLS = {
  cityFacilities: CITY_FACILITIES_URL,
  cityAddressData: CITY_ADDRESS_DATA_URL,
  barrieLibrary: BARRIE_LIBRARY_URL,
  publicSchools: SCDSB_URL,
  catholicSchools: SMCDSB_URL,
  openStreetMap: OPENSTREETMAP_URL,
};
